name: rsapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  google_sign_in: ^4.0.0
  firebase_core: ^0.4.0+8
  firebase_auth: ^0.14.0+1
  cloud_firestore: ^0.12.7+1
  firebase_storage: ^3.0.5

  # UI
  percent_indicator: ^2.1.1

  # Design
  provider: ^3.0.0
  path_provider: ^1.1.0

  # local storage
  sqflite: ^1.1.0

  # other
  json_serializable: ^2.0.0
  logger: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.2+1

flutter_icons:
  image_path_android: "res/launcher/icon.png"
  image_path_ios: "res/launcher/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "res/launcher/adaptive_icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - res/json/
    - res/icons/
    - res/charIcons/
    - res/letters/

