name: rsapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Design
  provider: ^3.0.0
  sqflite: ^1.1.0
  path_provider: ^1.1.0

  # UI
  percent_indicator: ^2.1.1
  fancy_bottom_navigation: ^0.3.2

  # log
  logger: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.2+1

flutter_icons:
  image_path_android: "res/launcher/icon.png"
  image_path_ios: "res/launcher/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "res/launcher/adaptive_icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - res/romasaga.txt
    - res/status_upper_limit.txt
    - res/icons/
    - res/charIcons/
    - res/letters/

