name: rsapp
description: Romancing Saga RS Status Management application.

version: 1.4.0+3

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  google_sign_in: ^4.5.1
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6

  # UI
  percent_indicator: ^2.1.5
  awesome_dialog: ^1.1.3
  progress_dialog: ^1.2.4

  # Design
  provider: ^4.1.3
  path_provider: ^1.6.11

  # local storage
  sqflite: ^1.3.1
  shared_preferences: ^0.5.7+3

  # network
  http: ^0.12.1
  cached_network_image: ^2.2.0+1

  # other
  package_info: ^0.4.1
  json_serializable: ^3.3.0
  logger: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.1

  flutter_launcher_icons: ^0.7.5

  pedantic: ^1.8.0+1

flutter_icons:
  image_path_android: "res/launcher/icon.png"
  image_path_ios: "res/launcher/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "res/launcher/adaptive_icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - res/json/
    - res/icons/
    - res/charIcons/

