name: rsapp
description: Romancing Saga Re:Universe Status Management application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  google_sign_in: ^4.0.11
  firebase_core: ^0.4.3+1
  firebase_auth: ^0.14.0+8
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.0.8

  # UI
  percent_indicator: ^2.1.1
  side_header_list_view: ^0.0.4

  # Design
  provider: ^3.0.0
  path_provider: ^1.5.1

  # local storage
  sqflite: ^1.1.0
  shared_preferences: ^0.5.3+4

  # network
  http: ^0.12.0+2
  cached_network_image: ^2.0.0-rc

  # other
  json_serializable: ^2.0.0
  logger: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.1

  flutter_launcher_icons: ^0.7.2+1

  pedantic: ^1.8.0+1

flutter_icons:
  image_path_android: "res/launcher/icon.png"
  image_path_ios: "res/launcher/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "res/launcher/adaptive_icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - res/json/
    - res/icons/
    - res/charIcons/

