name: rsapp
description: Romancing Saga RS Status Management application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+12

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # design
  flutter_riverpod: ^0.14.0+3
  freezed_annotation: ^0.14.1+3

  # Firebase
  google_sign_in: ^5.2.0
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  cloud_firestore: ^2.5.4
  firebase_storage: ^10.0.6
  firebase_crashlytics: ^2.2.4

  # UI
  percent_indicator: ^3.4.0
  awesome_dialog: ^2.1.1
  progress_dialog: ^1.2.4
  flutter_radar_chart: ^0.2.0

  # Design
  path_provider: ^2.0.5

  # local storage
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.8

  # network
  http: ^0.13.4
  cached_network_image: ^3.1.0

  # other
  package_info: ^2.0.2
  logger: ^1.1.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^0.14.1+3
  json_serializable: ^6.0.1
  hive_generator: ^1.1.0
  build_runner: ^2.0.1

  mockito: ^5.0.16

  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4

flutter_icons:
  android: false
  ios: true
  image_path: 'res/launcher/ic_launcher.png'

flutter:
  uses-material-design: true

  assets:
    - res/json/
    - res/icons/
    - res/charIcons/
    - res/logos/
