name: rsapp
description: Romancing Saga RS Status Management application.

version: 1.6.4+11

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  google_sign_in: ^4.5.5
  firebase_core: ^0.5.1
  firebase_auth: ^0.18.2
  cloud_firestore: ^0.14.2
  firebase_storage: ^4.0.1
  firebase_crashlytics: ^0.2.2

  # UI
  percent_indicator: ^2.1.8
  awesome_dialog: ^1.2.1
  progress_dialog: ^1.2.4
  flutter_radar_chart: ^0.1.6

  # Design
  provider: ^4.3.2
  path_provider: ^1.6.22

  # local storage
  sqflite: ^1.3.1
  shared_preferences: ^0.5.12+2

  # network
  http: ^0.12.2
  cached_network_image: ^2.3.3
  freezed: ^0.12.2

  # other
  package_info: ^0.4.3
  logger: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.3

  flutter_launcher_icons: ^0.8.1

  pedantic: ^1.8.0+1
  build_runner: ^1.10.0

flutter_icons:
  image_path_android: "res/launcher/icon.png"
  image_path_ios: "res/launcher/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "res/launcher/adaptive_icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - res/json/
    - res/icons/
    - res/charIcons/
    - res/logos/

