name: rsapp
description: Romancing Saga RS Status Management application.

publish_to: 'none'

version: 2.4.0+22

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # design
  flutter_riverpod: ^2.0.2
  riverpod_annotation: ^1.0.4
  freezed_annotation: ^2.1.0

  # Firebase
  google_sign_in: ^5.2.0
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  cloud_firestore: ^2.5.3
  firebase_storage: ^10.0.6
  firebase_crashlytics: ^2.2.4

  # UI
  percent_indicator: ^3.4.0
  progress_dialog: ^1.2.4
  modal_bottom_sheet: ^2.0.0
  webview_flutter: ^2.0.10
  cached_video_player: ^2.0.0-dev.1

  # local storage
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.8

  # network
  http: ^0.13.4
  cached_network_image: ^3.1.0

  # other
  package_info: ^2.0.2
  logger: ^1.1.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  riverpod_generator: ^1.0.4
  freezed: ^2.2.0
  json_serializable: ^6.5.1
  hive_generator: ^1.1.0
  build_runner: ^2.0.1

  path_provider: ^2.0.5
  mockito: ^5.3.1

  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0

flutter_icons:
  android: false
  ios: true
  image_path: 'res/launcher/ic_launcher.png'

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/launcher/
    - assets/logos/
